name = "Mndvn"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0a5013f0f6cfbfe3b65ec14cf982da033a80e5f87e77e6cd950f16a5b46c230"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
