name = "Mndvn"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dee6d0c07ddbbb790f47e18c24989e692e53e38cd4ab49e2743efb4a19bd5bcf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
