name = "Mndvn"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e2e5d808b337c1e1dbe966bb14f06cb7a768a4000918c79627e30a3a1039c9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
